import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState, useRef } from 'react'
//@ts-ignore: Unreachable code error
import WAVES from "vanta/dist/vanta.waves.min.js";
import * as THREE from "three";
import { ItemCard } from '../src/components/ItemCard'
import { UserIcon } from '@heroicons/react/solid'
import { ShoppingCartIcon } from '@heroicons/react/solid'

const Home: NextPage = () => {
  const [vantaEffect, setVantaEffect] = useState<any>(0);
  const vantaRef = useRef(null);
  useEffect(() => {
    if(!vantaEffect){
      setVantaEffect(
        WAVES({
          el: vantaRef.current,
          THREE,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 200.00,
          minWidth: 200.00,
          scale: 1.00,
          scaleMobile: 1.00,
          // color: 0x2e9d89,
          color: 0x88267,
          shininess: 37.00,
          waveHeight: 21.50,
          waveSpeed:  0.55,
          zoom: 1.09,
        })
      )
    }
    return () => {
      if (vantaEffect) vantaEffect.destory();
    }
  },[vantaEffect])

  return (
    <div className='w-screen h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen relative flex-1'>
        <section className='w-screen h-4/5 flex flex-column py-12' ref={vantaRef}>
          <nav className='absolute flex flex-row justify-center top-0 right-0 px-6 py-4 text-white'>
            <UserIcon className="h-6 w-6"/>
            <p className='text-xl mr-4'>LOGIN</p>
            <ShoppingCartIcon className="h-6 w-6"/>
            <p className='text-xl'>SHOP</p>
          </nav>
          <header className='w-screen py-4 px-6 my-auto text-center text-white'>
            <h1 className='mb-4 text-4xl font-bold'>3D FURNITURE</h1>
            <h2 className='italic text-2xl'>Find your perfect match!</h2>
          </header>
        </section>
        <div>
          <h1 className='text-3xl text-center my-8 text-zinc-600'>Products:</h1>
          <ItemCard />

        </div>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
