import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState, useRef } from 'react'
   // @ts-ignore: Unreachable code error
import WAVES from "vanta/dist/vanta.waves.min.js";
import * as THREE from "three";
import { ItemCard } from '../src/components/ItemCard'

const Home: NextPage = () => {
  const [vantaEffect, setVantaEffect] = useState<any>(0);
  const vantaRef = useRef(null);
  useEffect(() => {
    if(!vantaEffect){
      setVantaEffect(
        WAVES({
          el: vantaRef.current,
          THREE,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 200.00,
          minWidth: 200.00,
          scale: 1.00,
          scaleMobile: 1.00,
          // color: 0x2e9d89,
          color: 0x6ca297,
          shininess: 57.00,
          waveHeight: 21.50,
          waveSpeed:  0.55,
          zoom: 1.09,
        })
      )
    }
    return () => {
      if (vantaEffect) vantaEffect.destory();
    }
  },[vantaEffect])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <section className={styles.main__intro} ref={vantaRef}>
          <nav className={styles.main__nav} >
            <p>LOGIN</p>
            <p>CHART</p>
          </nav>
          <header className={styles.main__header}>
            <h1>3D FURNITURE</h1>
            <h2>Find your perfect match!</h2>
          </header>
        </section>
        <div className={styles.main__items}>
          <h1>Products:</h1>
          <ItemCard />
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
